### PR TITLE
add srcset to whitelist for img tags

### PR DESCRIPTION
**Pull request by emmericp**
Allows using HiDPI images

### CODE REVIEW

**Comment by simeonwillbanks** [comment]
@emmericp This appears to be a GitHub.com feature request.  GitHub has it's own `html-pipeline` filters, so this isn't the best place to address feature requests.

> [If anyone ... has a markup related feature request, please write in to support@github.com. It'll be easier for us to track from there. Thanks!](https://github.com/jch/html-pipeline/pull/39#issuecomment-72510219)

— @jch 

For now, I'm closing this Pull Request.  If you have any questions, please feel free to ask.  Thanks for understanding and the Pull Request!

**Comment by emmericp** [comment]
Yes, my original motivation for this PR was, of course, to get support for `srcset` on github.

However, this change makes sense for this project regardless of the motivation for the change:
`sanitization_filter.rb` defines a reasonable whitelist of tags and attributes.
`src` for `img` tags is one of them. Is there any good reason to *not* add the attribute `srcset` which is basically a modernized in version of `src`?

The only reason `srcset` is currently not supported is that the whitelist is older (2012 [1]) than the first proposal of the `srcset` attribute (2013 [2]). If this module was written today, you'd certainly include it from the beginning without a second thought. Why not update the whitelist?



[1] https://github.com/jch/html-pipeline/blame/master/lib/html/pipeline/sanitization_filter.rb#L53
[2] http://www.w3.org/TR/2013/WD-html-srcset-20130228/

**Comment by tabatkins** [comment]
A year later, can we reopen this?  It's still the case that the exclusion of `srcset` appears to be a historical accident (the whitelist was written before the attribute was added to the spec), and allowing `srcset` is *precisely* as safe as allowing `src`.

You can trust me on that last point, *because I'm the person that wrote most of the srcset spec that was eventually merged into HTML*.

**Comment by Kukunin** [comment]
👍

**Comment by tabatkins** [comment]
Year-later ping for hopeful reopening?

**Comment by emmericp** [comment]
This probably would have been merge if I hadn't mentioned *why* I wanted that feature.
Sorry for ruining it for you too :(

**Comment by Kukunin** [comment]
@emmericp it's a really pity. I still hope that in 2k17 we will have ability to inject HiDPI images to all projects that use `html-pipeline`

**Pull request closed without merging**
