### PR TITLE
Bump Active Support dependency to version >= 2

### LINKED ISSUE #252: Rails 5 support
Will html-pipeline be updated with ActiveSupport 5 and therefore Rails 5 support any time soon?

### PR DESCRIPTION
**Pull request by JuanitoFatas**
Closes #252 

This Pull Request unlocks Active Support dependency to `>= 2`, so that App used `HTML::Pipeline` can upgrade to [Rails 5](http://weblog.rubyonrails.org/2016/6/30/Rails-5-0-final/).

## Changes

- [x] Setup Test Matrix with [thoughtbot/appraisal](https://github.com/thoughtbot/appraisal) ea9a723
- [x] Avoid the use of `try` because Rails 3 behavior breaks 788a2da
- [x] Only pack necessary file to released gem 7925b72

## Appraisal Usage

- Run tests with Rails 3: `$ appraisal rails-3 rake`
- Run tests with Rails 4: `$ appraisal rails-4 rake`
- Run tests with Rails 5: `$ appraisal rails-5 rake`
- Run above all combined: `$ appraisal rake`

## Exclude builds

- [Rails 5 required Ruby version is `2.2.2`](https://github.com/rails/rails/blob/49fe7c66874b7b92ff1587b35777a760ac75be9b/rails.gemspec#L10), so [exclude Ruby version < 2.2.2 build with Rails 5](https://github.com/jch/html-pipeline/blob/a31fa29f891f471a071cc4cb0036cbeb178b63a8/.travis.yml#L28-L32).

## Allowed Failures

screenshot 2016-07-03 16 25 17

`ruby-head` is nice to pass, but failed is fine.

## Test with Rails 5 apps

`HTML::Pipeline` works great with these Rails 5.0.0 apps:

- [JuanitoFatas/markdown][markdown], [Build Result](https://travis-ci.org/JuanitoFatas/markdown/builds/141573590)
- [RedDotRubyConf/rdrc2016][rdrc2016], [Build Result](https://travis-ci.org/reddotrubyconf/rdrc2016/builds/141537934)
- [Thredded](https://github.com/thredded/thredded) [reported running on Rails 5 without problems](https://www.reddit.com/r/ruby/comments/4r0rob/anyone_use_htmlpipeline_on_rails_5/d4xxqwv)

[markdown]: https://github.com/JuanitoFatas/markdown
[rdrc2016]: https://github.com/RedDotRubyConf/rdrc2016

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
@jch @simeonwillbanks 👍 ?

**Comment by jch** [comment]
Sorry, I haven't had a chance to test this on Rails 5 yet. In addition to the tests, has this been used in a production app yet? We're still using a patched version of Rails 3 and moving towards 4.

**Comment by JuanitoFatas** [comment]
> has this been used in a production app yet?

Yes, the [RedDotRubyConf](http://reddotrubyconf.com) webiste [uses HTML::Pipeline](https://github.com/reddotrubyconf/rdrc2016/commit/fdea75f9763ffdd12748fbff0e1c7e32d05688cc). And I created [a Rails 5 app](https://github.com/JuanitoFatas/makedown) with [some specs](https://github.com/JuanitoFatas/markdown/blob/master/spec/models/render_markdown_spec.rb).

For tests: I can setup a test suite with https://github.com/thoughtbot/appraisal. But I am also thinking create some real apps and put them under github.com/html-pipeline organization, what do you think?

**Comment by JuanitoFatas** [comment]
@jch Please review and 🚢 :shipit: ❤️

**Comment by bdewater** [comment]
Instead of `allow_failures` for Rails 5 and Ruby versions < 2.2.2, use [`exclude`](https://docs.travis-ci.com/user/customizing-the-build/#Excluding-Jobs) to save CPU time on Travis.

**Comment by JuanitoFatas** [comment]
> Instead of allow_failures for Rails 5 and Ruby versions < 2.2.2, use exclude to save CPU time on Travis.

Thanks Bart! ❤️ Updated `.travis.yml` in a31fa29.

**Comment by glebm** [comment]
> has this been used in a production app yet?

Also now running on with https://thredded.org/ with Rails 5.0.0 and this PR as of this comment.

**Comment by n-rodriguez** [comment]
hi there! any news?

**Comment by parkr** [comment]
@jch Just so you know, this has caused muchas problemas for systems using Ruby < 2.2.2, which isn't smart enough to install activesupport v4.x:

- https://travis-ci.org/github/pages-gem/builds/144818057
- https://travis-ci.org/github/pages-gem/builds/144818070
- https://github.com/jekyll/jekyll/pull/5100
- https://travis-ci.org/jekyll/jekyll/jobs/144208193#L465
- ... etc

**Comment by jch** [comment]
@parkr good catch. This has been a frustration each time html-pipeline upgrades it's dependencies be because of it's loose constraints on versions. I proposed splitting up the gem into smaller gems to narrow down these problems in https://github.com/jch/html-pipeline/issues/182, but did not make any changes at the time.

Could you talk more about why this is breaking for specific versions of Ruby? What workaround have you taken for it?

**Comment by parkr** [comment]
> Could you talk more about why this is breaking for specific versions of Ruby?

Absolutely. The issue affects anyone installing `jemoji` or `jekyll-mentions`, two gems which rely on this gem (bindings for the emoji filter and mentions filter, respectively). When one specifies `gem "jekyll-mentions"` in one's `Gemfile` and executes `bundle install`, they see the error saying that `activesupport 5.0.0 requires Ruby 2.2.2 or higher to install`. Instead of gracefully downgrading to activesupport 4.2.7, it simply fails. The two plugins I mentioned above simply specify their dependency on `html-pipeline`. Neither bundler nor RubyGems for Ruby 2.1 appear to be able to gracefully downgrade a dependency until they all resolve to installable versions.

> What workaround have you taken for it?

The workaround we went for is to lock down `activesupport` to `~> 4.0` (e.g. jekyll/jemoji#47) as it is compatible with all Ruby versions we test with (2.0, 2.1, 2.2, 2.3). I looked at the emoji filter and all activesupport is used for is `HashWithIndifferentAccess`. :frowning: Perhaps we could remove that dependency on the emoji filter?

**Comment by JuanitoFatas** [comment]
> The workaround we went for is to lock down activesupport to ~> 4.0 (e.g. jekyll/jemoji#47) as it is compatible with all Ruby versions we test with (2.0, 2.1, 2.2, 2.3).

How about release a patch version of Jemoji that stays with Active Support 4.x and a new major version that supports Active Support 5+? 😅 

> I looked at the emoji filter and all activesupport is used for is HashWithIndifferentAccess. 😦 Perhaps we could remove that dependency on the emoji filter?

If we want to remove Active Support, we need to remove all usage of Active Support across the html-pipeline gem. Otherwise html-pipeline still depend on Active Support. The barrier is the use of [coverting document to hash](https://github.com/jch/html-pipeline/blob/78115f63bd499c25922f3dd77c8fd3db3c54ed51/lib/html/pipeline.rb#L2). 😓

**Comment by parkr** [comment]
> How about release a patch version of Jemoji that stays with Active Support 4.x

We did this, actually. GitHub Pages uses Ruby 2.1.7 in production so we locked the downgrade and all was well.

It's not the end of the world, but there were a couple days where anyone using Ruby < 2.2.2 couldn't install this gem.

**Comment by Taher-Ghaleb** [comment]
Hello,

Sorry, I know it's been a long time ago, but I am curious why caching hasn't been enabled before this (i.e., since December 17, 2014, when it became available to open source projects).

Thank you.

**Pull request merged**
