### PR TITLE
Reduce travis errors and move to trusty

### PR DESCRIPTION
**Pull request by timdiggins**
This is a replacement to #283 which:

* brings travis to trusty (with sudo: false it results in travis throwing away source: libicu-dev, but everything seems to install and run ok, so maybe that source is no longer needed on trusty?)
* improves reliability of bundle install on travis by deleting the .lock files for specific gemfiles and overriding/removing the --deployment option to bundler so that bundler will never complain about the gemfile.lock being updated, and will always use latest dependencies (similar to a current clean install on any system)

### CODE REVIEW

**Comment by gjtorikian** [comment]
Given that e27f50a7676480511e91f897ca56cc34a5fbcb9b passed, why is `dist: trusty` necessary?

**Comment by timdiggins** [comment]
> Given that e27f50a passed, why is dist: trusty necessary?

@gjtorikian because travis is moving its default from precise to trusty anytime now, I thought it would be better to be specific (rather than just wait for it possibly to fail). True, it has now succeeded so could just wait for the automatic default to change, but I think the more predictability in CI the better

**Comment by gjtorikian** [comment]
> but I think the more predictability in CI the better

My concern is that we will forget to remove or change this value when Travis inevitable moves off of `trusty` and onto The Next Great Thing, leaving us stuck in the past.

Given that this PR works with the current Travis setup _and_ the future Travis setup I'm going to go ahead and merge it but take that line out.

**Comment by gjtorikian** [comment]
Thank you!

**Pull request merged**
