### PR TITLE
Only allow cite attribute on blockquote and restrict schemes

### PR DESCRIPTION
**Pull request by mastahyeti**
This limits the schemes that can be used with the `cite` attribute on blockquote elements.

/cc @jch @ytrezq @oreoshake @ptoomey3 @gregose

### CODE REVIEW

**Comment by ytrezq** [comment]
@mastahyeti : Did you opened it because you checked September 26 e‑mails or because I updated the comment.

Also why restrict it only for blockquote ? Why not doing it the same way as [sanitize.rb](https://github.com/rgrove/sanitize/blob/master/lib/sanitize/config/basic.rb) in it’s basic configuration ?

**Comment by mastahyeti** [comment]
> I hope this change will also takes place on GitHub’s owned web sites !

Yeah, we've run into some trouble updating the Gem on our servers because of some incompatibilities with internal libraries. We're working on fixing this.

> Also why restrict it only to blockquote ?

From my searches, the `cite` attribute is only allowed on `blockquote` tags.

> Why not doing it the same way as sanitize.rb inside it’s basic configuration ?

Because GitHub doesn't make use of the whitelist in that Gem. I'm sure rgrove would appreciate a pull request though.

**Comment by ytrezq** [comment]
@mastahyeti : As [per ᴡ3ᴄ spec](http://www.w3.org/html/wg/drafts/html/master/index.html#attributes-1) It’s a valid attribute on “blockquote; del; ins; q”

**Comment by mastahyeti** [comment]
Thanks for finding that @ytrezq. Apparently, I didn't Google hard enough :smile:. I updated this PR.

**Comment by ytrezq** [comment]
@mastahyeti : You definitely have comprehension troubles. I told “There is pending ᴘʀ on your repository for reflecting the spec on this ᴘʀ.”

But apparently you’re prefering [doing the work twice](https://github.com/mastahyeti/html-pipeline/pull/1)

**Comment by jch** [comment]
Diff is easier to read when turning off whitespace: https://github.com/jch/html-pipeline/pull/223/files?w=1

Looks good to me :+1:

**Pull request merged**
