### PR TITLE
Release 2.2.0

### PR DESCRIPTION
**Pull request by jch**
cc @mastahyeti

### CODE REVIEW

**Comment by mastahyeti** [comment]
:+1:

**Comment by jch** [comment]
2.2.0 released https://rubygems.org/gems/html-pipeline/versions/2.2.0

**Comment by mastahyeti** [comment]
Thanks!

**Comment by kbrock** [comment]
:+1: thanks

**Comment by ytrezq** [comment]
@mastahyeti : Sorry for telling it here. But can you check you e‑mails replies ?

**Pull request merged**
