### PR TITLE
Release 2.1.0

### PR DESCRIPTION
**Pull request by jch**
cc @mastahyeti @ptoomey3 @kbrock @st0012

### CODE REVIEW

**Comment by mastahyeti** [comment]
:+1: thanks!

On Tue, Sep 22, 2015 at 1:56 PM, Jerry Cheung <notifications@github.com>
wrote:

> cc @mastahyeti <https://github.com/mastahyeti> @ptoomey3
> <https://github.com/ptoomey3> @kbrock <https://github.com/kbrock> @st0012
> <https://github.com/st0012>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jch/html-pipeline/pull/222
> Commit Summary
>
>    - update script/changelog
>    - release 2.1.0
>
> File Changes
>
>    - *M* CHANGELOG.md
>    <https://github.com/jch/html-pipeline/pull/222/files#diff-0> (7)
>    - *M* lib/html/pipeline/version.rb
>    <https://github.com/jch/html-pipeline/pull/222/files#diff-1> (2)
>    - *M* script/changelog
>    <https://github.com/jch/html-pipeline/pull/222/files#diff-2> (37)
>
> Patch Links:
>
>    - https://github.com/jch/html-pipeline/pull/222.patch
>    - https://github.com/jch/html-pipeline/pull/222.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jch/html-pipeline/pull/222>.
>



-- 
-Ben Toews

**Comment by jch** [comment]
https://rubygems.org/gems/html-pipeline/versions/2.1.0 :tada:

**Comment by st0012** [comment]
:+1:

**Comment by kbrock** [comment]
:+1:

**Pull request merged**
