### PR TITLE
Add Flickr filter

### PR DESCRIPTION
**Pull request by st0012**
It converts flickr's link into a linkable image

### CODE REVIEW

**Comment by jch** [comment]
Thanks for the pull! The code looks fine, but I think it belongs in it's own separate gem because it isn't a general filter. If you do create one, let me know, and I can link it from [the readme](https://github.com/jch/html-pipeline#3rd-party-extensions). Closing https://github.com/jch/html-pipeline/pull/209 for the same reason.

**Comment by st0012** [comment]
Ok, thx

**Comment by st0012** [comment]
@jch I just create [html-pipeline-youtube](https://github.com/st0012/html-pipeline-youtube) gem for youtube filter. You can check it through the link, thanks for your advice.

**Comment by jch** [comment]
Updated readme to link to your project https://github.com/jch/html-pipeline/commit/c2350a09b1fdec7806076418bc5fbf732e9eb02e

**Comment by st0012** [comment]
@jch thank you

**Pull request closed without merging**
